# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_ui_dual_spectrum.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1900, 1000)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dataViewerTab = QtWidgets.QTabWidget(self.centralwidget)
        self.dataViewerTab.setGeometry(QtCore.QRect(590, 10, 1300, 945))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataViewerTab.sizePolicy().hasHeightForWidth())
        self.dataViewerTab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataViewerTab.setFont(font)
        self.dataViewerTab.setAutoFillBackground(True)
        self.dataViewerTab.setObjectName("dataViewerTab")
        self.DataAcqTab = QtWidgets.QWidget()
        self.DataAcqTab.setStyleSheet("background-color: rgb(83, 83, 83);")
        self.DataAcqTab.setObjectName("DataAcqTab")
        self.graphicsViewSampleSpecSeries = GraphicsView(self.DataAcqTab)
        self.graphicsViewSampleSpecSeries.setGeometry(QtCore.QRect(450, 400, 410, 250))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.graphicsViewSampleSpecSeries.sizePolicy().hasHeightForWidth())
        self.graphicsViewSampleSpecSeries.setSizePolicy(sizePolicy)
        self.graphicsViewSampleSpecSeries.setMinimumSize(QtCore.QSize(0, 200))
        self.graphicsViewSampleSpecSeries.setObjectName("graphicsViewSampleSpecSeries")
        self.graphicsViewSampleSpectrum = GraphicsView(self.DataAcqTab)
        self.graphicsViewSampleSpectrum.setGeometry(QtCore.QRect(450, 140, 410, 250))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.graphicsViewSampleSpectrum.sizePolicy().hasHeightForWidth())
        self.graphicsViewSampleSpectrum.setSizePolicy(sizePolicy)
        self.graphicsViewSampleSpectrum.setMinimumSize(QtCore.QSize(0, 0))
        self.graphicsViewSampleSpectrum.setObjectName("graphicsViewSampleSpectrum")
        self.graphicsViewSample = GraphicsView(self.DataAcqTab)
        self.graphicsViewSample.setGeometry(QtCore.QRect(450, 30, 410, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.graphicsViewSample.sizePolicy().hasHeightForWidth())
        self.graphicsViewSample.setSizePolicy(sizePolicy)
        self.graphicsViewSample.setMinimumSize(QtCore.QSize(410, 100))
        self.graphicsViewSample.setObjectName("graphicsViewSample")
        self.graphicsViewSampleScanDepth = GraphicsView(self.DataAcqTab)
        self.graphicsViewSampleScanDepth.setGeometry(QtCore.QRect(450, 660, 410, 250))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.graphicsViewSampleScanDepth.sizePolicy().hasHeightForWidth())
        self.graphicsViewSampleScanDepth.setSizePolicy(sizePolicy)
        self.graphicsViewSampleScanDepth.setMinimumSize(QtCore.QSize(0, 0))
        self.graphicsViewSampleScanDepth.setObjectName("graphicsViewSampleScanDepth")
        self.graphicsViewHeatmap = GraphicsView(self.DataAcqTab)
        self.graphicsViewHeatmap.setGeometry(QtCore.QRect(10, 495, 430, 415))
        self.graphicsViewHeatmap.setObjectName("graphicsViewHeatmap")
        self.graphicsViewCMOS = GraphicsView(self.DataAcqTab)
        self.graphicsViewCMOS.setGeometry(QtCore.QRect(10, 30, 430, 415))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsViewCMOS.sizePolicy().hasHeightForWidth())
        self.graphicsViewCMOS.setSizePolicy(sizePolicy)
        self.graphicsViewCMOS.setMinimumSize(QtCore.QSize(430, 415))
        self.graphicsViewCMOS.setObjectName("graphicsViewCMOS")
        self.graphicsViewCalibSpectrum = GraphicsView(self.DataAcqTab)
        self.graphicsViewCalibSpectrum.setGeometry(QtCore.QRect(870, 140, 410, 250))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.graphicsViewCalibSpectrum.sizePolicy().hasHeightForWidth())
        self.graphicsViewCalibSpectrum.setSizePolicy(sizePolicy)
        self.graphicsViewCalibSpectrum.setMinimumSize(QtCore.QSize(0, 0))
        self.graphicsViewCalibSpectrum.setObjectName("graphicsViewCalibSpectrum")
        self.graphicsViewCalibSpecSeries = GraphicsView(self.DataAcqTab)
        self.graphicsViewCalibSpecSeries.setGeometry(QtCore.QRect(870, 400, 410, 250))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.graphicsViewCalibSpecSeries.sizePolicy().hasHeightForWidth())
        self.graphicsViewCalibSpecSeries.setSizePolicy(sizePolicy)
        self.graphicsViewCalibSpecSeries.setMinimumSize(QtCore.QSize(0, 200))
        self.graphicsViewCalibSpecSeries.setObjectName("graphicsViewCalibSpecSeries")
        self.graphicsViewCalib = GraphicsView(self.DataAcqTab)
        self.graphicsViewCalib.setGeometry(QtCore.QRect(870, 30, 410, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.graphicsViewCalib.sizePolicy().hasHeightForWidth())
        self.graphicsViewCalib.setSizePolicy(sizePolicy)
        self.graphicsViewCalib.setMinimumSize(QtCore.QSize(410, 100))
        self.graphicsViewCalib.setObjectName("graphicsViewCalib")
        self.graphicsViewCalibScanDepth = GraphicsView(self.DataAcqTab)
        self.graphicsViewCalibScanDepth.setGeometry(QtCore.QRect(870, 660, 410, 250))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.graphicsViewCalibScanDepth.sizePolicy().hasHeightForWidth())
        self.graphicsViewCalibScanDepth.setSizePolicy(sizePolicy)
        self.graphicsViewCalibScanDepth.setMinimumSize(QtCore.QSize(0, 0))
        self.graphicsViewCalibScanDepth.setObjectName("graphicsViewCalibScanDepth")
        self.session_label_2 = QtWidgets.QLabel(self.DataAcqTab)
        self.session_label_2.setGeometry(QtCore.QRect(10, 470, 430, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.session_label_2.setFont(font)
        self.session_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.session_label_2.setObjectName("session_label_2")
        self.session_label_3 = QtWidgets.QLabel(self.DataAcqTab)
        self.session_label_3.setGeometry(QtCore.QRect(450, 5, 410, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.session_label_3.setFont(font)
        self.session_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.session_label_3.setObjectName("session_label_3")
        self.session_label_4 = QtWidgets.QLabel(self.DataAcqTab)
        self.session_label_4.setGeometry(QtCore.QRect(870, 5, 410, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.session_label_4.setFont(font)
        self.session_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.session_label_4.setObjectName("session_label_4")
        self.session_label_5 = QtWidgets.QLabel(self.DataAcqTab)
        self.session_label_5.setGeometry(QtCore.QRect(10, 5, 430, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.session_label_5.setFont(font)
        self.session_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.session_label_5.setObjectName("session_label_5")
        self.dataViewerTab.addTab(self.DataAcqTab, "")
        self.DataViewTab = QtWidgets.QWidget()
        self.DataViewTab.setStyleSheet("background-color: rgb(83, 83, 83);")
        self.DataViewTab.setObjectName("DataViewTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.DataViewTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.dataViewScanDepth = GraphicsView(self.DataViewTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.dataViewScanDepth.sizePolicy().hasHeightForWidth())
        self.dataViewScanDepth.setSizePolicy(sizePolicy)
        self.dataViewScanDepth.setObjectName("dataViewScanDepth")
        self.gridLayout_4.addWidget(self.dataViewScanDepth, 6, 1, 1, 1)
        self.dataViewSpecSeries = GraphicsView(self.DataViewTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.dataViewSpecSeries.sizePolicy().hasHeightForWidth())
        self.dataViewSpecSeries.setSizePolicy(sizePolicy)
        self.dataViewSpecSeries.setObjectName("dataViewSpecSeries")
        self.gridLayout_4.addWidget(self.dataViewSpecSeries, 5, 1, 1, 1)
        self.dataViewSingleSpectrum = GraphicsView(self.DataViewTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.dataViewSingleSpectrum.sizePolicy().hasHeightForWidth())
        self.dataViewSingleSpectrum.setSizePolicy(sizePolicy)
        self.dataViewSingleSpectrum.setMinimumSize(QtCore.QSize(0, 200))
        self.dataViewSingleSpectrum.setObjectName("dataViewSingleSpectrum")
        self.gridLayout_4.addWidget(self.dataViewSingleSpectrum, 4, 1, 1, 1)
        self.dataViewInfoDisplay = QtWidgets.QLabel(self.DataViewTab)
        self.dataViewInfoDisplay.setStyleSheet("color: rgb(255, 255, 255);")
        self.dataViewInfoDisplay.setObjectName("dataViewInfoDisplay")
        self.gridLayout_4.addWidget(self.dataViewInfoDisplay, 0, 1, 1, 1)
        self.dataViewSlider = QtWidgets.QSlider(self.DataViewTab)
        self.dataViewSlider.setOrientation(QtCore.Qt.Horizontal)
        self.dataViewSlider.setObjectName("dataViewSlider")
        self.gridLayout_4.addWidget(self.dataViewSlider, 1, 1, 1, 1)
        self.dataViewEMCCD = GraphicsView(self.DataViewTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dataViewEMCCD.sizePolicy().hasHeightForWidth())
        self.dataViewEMCCD.setSizePolicy(sizePolicy)
        self.dataViewEMCCD.setMinimumSize(QtCore.QSize(400, 100))
        self.dataViewEMCCD.setObjectName("dataViewEMCCD")
        self.gridLayout_4.addWidget(self.dataViewEMCCD, 3, 1, 1, 1)
        self.graphicsViewCMOSViewer = GraphicsView(self.DataViewTab)
        self.graphicsViewCMOSViewer.setObjectName("graphicsViewCMOSViewer")
        self.gridLayout_4.addWidget(self.graphicsViewCMOSViewer, 2, 0, 3, 1)
        self.graphicsViewHeatmapViewer = GraphicsView(self.DataViewTab)
        self.graphicsViewHeatmapViewer.setObjectName("graphicsViewHeatmapViewer")
        self.gridLayout_4.addWidget(self.graphicsViewHeatmapViewer, 5, 0, 2, 1)
        self.dataViewTextEdit = QtWidgets.QTextEdit(self.DataViewTab)
        self.dataViewTextEdit.setObjectName("dataViewTextEdit")
        self.gridLayout_4.addWidget(self.dataViewTextEdit, 2, 1, 1, 1)
        self.dataViewerTab.addTab(self.DataViewTab, "")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(280, 10, 300, 941))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMinimumSize(QtCore.QSize(300, 0))
        self.treeView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeView.setObjectName("treeView")
        self.parameterTreeWidget = ParameterTree(self.centralwidget)
        self.parameterTreeWidget.setGeometry(QtCore.QRect(10, 70, 260, 881))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.parameterTreeWidget.sizePolicy().hasHeightForWidth())
        self.parameterTreeWidget.setSizePolicy(sizePolicy)
        self.parameterTreeWidget.setMinimumSize(QtCore.QSize(260, 0))
        self.parameterTreeWidget.setAnimated(True)
        self.parameterTreeWidget.setHeaderHidden(True)
        self.parameterTreeWidget.setObjectName("parameterTreeWidget")
        self.parameterTreeWidget.headerItem().setText(0, "1")
        self.sessionName = QtWidgets.QLineEdit(self.centralwidget)
        self.sessionName.setEnabled(True)
        self.sessionName.setGeometry(QtCore.QRect(10, 34, 165, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sessionName.setFont(font)
        self.sessionName.setText("")
        self.sessionName.setAlignment(QtCore.Qt.AlignCenter)
        self.sessionName.setReadOnly(True)
        self.sessionName.setObjectName("sessionName")
        self.session_label = QtWidgets.QLabel(self.centralwidget)
        self.session_label.setGeometry(QtCore.QRect(10, 13, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.session_label.setFont(font)
        self.session_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.session_label.setObjectName("session_label")
        self.newSessionBtn = QtWidgets.QPushButton(self.centralwidget)
        self.newSessionBtn.setGeometry(QtCore.QRect(186, 39, 85, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.newSessionBtn.setFont(font)
        self.newSessionBtn.setObjectName("newSessionBtn")
        self.loadSessionBtn = QtWidgets.QPushButton(self.centralwidget)
        self.loadSessionBtn.setGeometry(QtCore.QRect(186, 10, 85, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loadSessionBtn.setFont(font)
        self.loadSessionBtn.setObjectName("loadSessionBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1900, 21))
        self.menubar.setObjectName("menubar")
        self.menuBrillouin_DAQ = QtWidgets.QMenu(self.menubar)
        self.menuBrillouin_DAQ.setObjectName("menuBrillouin_DAQ")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuBrillouin_DAQ.menuAction())

        self.retranslateUi(MainWindow)
        self.dataViewerTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Brillouin Scanning Interface"))
        self.session_label_2.setText(_translate("MainWindow", "Brillouin Map"))
        self.session_label_3.setText(_translate("MainWindow", "Sample Spectrum"))
        self.session_label_4.setText(_translate("MainWindow", "Reference Spectrum"))
        self.session_label_5.setText(_translate("MainWindow", "Live Video"))
        self.dataViewerTab.setTabText(self.dataViewerTab.indexOf(self.DataAcqTab), _translate("MainWindow", "Data Acquisition"))
        self.dataViewInfoDisplay.setText(_translate("MainWindow", "Frame 0/0 "))
        self.dataViewerTab.setTabText(self.dataViewerTab.indexOf(self.DataViewTab), _translate("MainWindow", "Data Viewer"))
        self.session_label.setText(_translate("MainWindow", "Session Name"))
        self.newSessionBtn.setText(_translate("MainWindow", "New Session"))
        self.loadSessionBtn.setText(_translate("MainWindow", "Load Session"))
        self.menuBrillouin_DAQ.setTitle(_translate("MainWindow", "Brillouin DAQ"))

from pyqtgraph.parametertree import ParameterTree
from pyqtgraph.widgets.GraphicsView import GraphicsView

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

