# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_ui_tabbed.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(2392, 1409)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.session_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.session_label.setFont(font)
        self.session_label.setAlignment(QtCore.Qt.AlignCenter)
        self.session_label.setObjectName(_fromUtf8("session_label"))
        self.gridLayout_3.addWidget(self.session_label, 0, 0, 1, 1)
        self.sessionName = QtGui.QLineEdit(self.centralwidget)
        self.sessionName.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sessionName.setFont(font)
        self.sessionName.setText(_fromUtf8(""))
        self.sessionName.setAlignment(QtCore.Qt.AlignCenter)
        self.sessionName.setReadOnly(True)
        self.sessionName.setObjectName(_fromUtf8("sessionName"))
        self.gridLayout_3.addWidget(self.sessionName, 1, 0, 1, 1)
        self.newSessionBtn = QtGui.QPushButton(self.centralwidget)
        self.newSessionBtn.setObjectName(_fromUtf8("newSessionBtn"))
        self.gridLayout_3.addWidget(self.newSessionBtn, 1, 1, 1, 1)
        self.loadSessionBtn = QtGui.QPushButton(self.centralwidget)
        self.loadSessionBtn.setObjectName(_fromUtf8("loadSessionBtn"))
        self.gridLayout_3.addWidget(self.loadSessionBtn, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.parameterTreeWidget = ParameterTree(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.parameterTreeWidget.sizePolicy().hasHeightForWidth())
        self.parameterTreeWidget.setSizePolicy(sizePolicy)
        self.parameterTreeWidget.setMinimumSize(QtCore.QSize(400, 0))
        self.parameterTreeWidget.setAnimated(True)
        self.parameterTreeWidget.setHeaderHidden(True)
        self.parameterTreeWidget.setObjectName(_fromUtf8("parameterTreeWidget"))
        self.parameterTreeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout.addWidget(self.parameterTreeWidget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.dataViewerTab = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataViewerTab.sizePolicy().hasHeightForWidth())
        self.dataViewerTab.setSizePolicy(sizePolicy)
        self.dataViewerTab.setObjectName(_fromUtf8("dataViewerTab"))
        self.DataAcqTab = QtGui.QWidget()
        self.DataAcqTab.setStyleSheet(_fromUtf8("background-color: rgb(83, 83, 83);"))
        self.DataAcqTab.setObjectName(_fromUtf8("DataAcqTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.DataAcqTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.graphicsViewSpecSeries = GraphicsView(self.DataAcqTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.graphicsViewSpecSeries.sizePolicy().hasHeightForWidth())
        self.graphicsViewSpecSeries.setSizePolicy(sizePolicy)
        self.graphicsViewSpecSeries.setObjectName(_fromUtf8("graphicsViewSpecSeries"))
        self.gridLayout_2.addWidget(self.graphicsViewSpecSeries, 3, 1, 1, 1)
        self.graphicsViewSingleSpectrum = GraphicsView(self.DataAcqTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.graphicsViewSingleSpectrum.sizePolicy().hasHeightForWidth())
        self.graphicsViewSingleSpectrum.setSizePolicy(sizePolicy)
        self.graphicsViewSingleSpectrum.setMinimumSize(QtCore.QSize(0, 200))
        self.graphicsViewSingleSpectrum.setObjectName(_fromUtf8("graphicsViewSingleSpectrum"))
        self.gridLayout_2.addWidget(self.graphicsViewSingleSpectrum, 2, 1, 1, 1)
        self.graphicsViewEMCCD = GraphicsView(self.DataAcqTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.graphicsViewEMCCD.sizePolicy().hasHeightForWidth())
        self.graphicsViewEMCCD.setSizePolicy(sizePolicy)
        self.graphicsViewEMCCD.setMinimumSize(QtCore.QSize(400, 100))
        self.graphicsViewEMCCD.setObjectName(_fromUtf8("graphicsViewEMCCD"))
        self.gridLayout_2.addWidget(self.graphicsViewEMCCD, 1, 1, 1, 1)
        self.graphicsViewScanDepth = GraphicsView(self.DataAcqTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.graphicsViewScanDepth.sizePolicy().hasHeightForWidth())
        self.graphicsViewScanDepth.setSizePolicy(sizePolicy)
        self.graphicsViewScanDepth.setObjectName(_fromUtf8("graphicsViewScanDepth"))
        self.gridLayout_2.addWidget(self.graphicsViewScanDepth, 4, 1, 1, 1)
        self.graphicsViewHeatmap = GraphicsView(self.DataAcqTab)
        self.graphicsViewHeatmap.setObjectName(_fromUtf8("graphicsViewHeatmap"))
        self.gridLayout_2.addWidget(self.graphicsViewHeatmap, 3, 0, 2, 1)
        self.graphicsViewCMOS = GraphicsView(self.DataAcqTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsViewCMOS.sizePolicy().hasHeightForWidth())
        self.graphicsViewCMOS.setSizePolicy(sizePolicy)
        self.graphicsViewCMOS.setMinimumSize(QtCore.QSize(200, 500))
        self.graphicsViewCMOS.setObjectName(_fromUtf8("graphicsViewCMOS"))
        self.gridLayout_2.addWidget(self.graphicsViewCMOS, 1, 0, 2, 1)
        self.dataViewerTab.addTab(self.DataAcqTab, _fromUtf8(""))
        self.DataViewTab = QtGui.QWidget()
        self.DataViewTab.setStyleSheet(_fromUtf8("background-color: rgb(83, 83, 83);"))
        self.DataViewTab.setObjectName(_fromUtf8("DataViewTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.DataViewTab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.dataViewScanDepth = GraphicsView(self.DataViewTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.dataViewScanDepth.sizePolicy().hasHeightForWidth())
        self.dataViewScanDepth.setSizePolicy(sizePolicy)
        self.dataViewScanDepth.setObjectName(_fromUtf8("dataViewScanDepth"))
        self.gridLayout_4.addWidget(self.dataViewScanDepth, 6, 1, 1, 1)
        self.dataViewSpecSeries = GraphicsView(self.DataViewTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.dataViewSpecSeries.sizePolicy().hasHeightForWidth())
        self.dataViewSpecSeries.setSizePolicy(sizePolicy)
        self.dataViewSpecSeries.setObjectName(_fromUtf8("dataViewSpecSeries"))
        self.gridLayout_4.addWidget(self.dataViewSpecSeries, 5, 1, 1, 1)
        self.dataViewSingleSpectrum = GraphicsView(self.DataViewTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.dataViewSingleSpectrum.sizePolicy().hasHeightForWidth())
        self.dataViewSingleSpectrum.setSizePolicy(sizePolicy)
        self.dataViewSingleSpectrum.setMinimumSize(QtCore.QSize(0, 200))
        self.dataViewSingleSpectrum.setObjectName(_fromUtf8("dataViewSingleSpectrum"))
        self.gridLayout_4.addWidget(self.dataViewSingleSpectrum, 4, 1, 1, 1)
        self.dataViewInfoDisplay = QtGui.QLabel(self.DataViewTab)
        self.dataViewInfoDisplay.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.dataViewInfoDisplay.setObjectName(_fromUtf8("dataViewInfoDisplay"))
        self.gridLayout_4.addWidget(self.dataViewInfoDisplay, 0, 1, 1, 1)
        self.dataViewSlider = QtGui.QSlider(self.DataViewTab)
        self.dataViewSlider.setOrientation(QtCore.Qt.Horizontal)
        self.dataViewSlider.setObjectName(_fromUtf8("dataViewSlider"))
        self.gridLayout_4.addWidget(self.dataViewSlider, 1, 1, 1, 1)
        self.dataViewEMCCD = GraphicsView(self.DataViewTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dataViewEMCCD.sizePolicy().hasHeightForWidth())
        self.dataViewEMCCD.setSizePolicy(sizePolicy)
        self.dataViewEMCCD.setMinimumSize(QtCore.QSize(400, 100))
        self.dataViewEMCCD.setObjectName(_fromUtf8("dataViewEMCCD"))
        self.gridLayout_4.addWidget(self.dataViewEMCCD, 3, 1, 1, 1)
        self.graphicsViewCMOSViewer = GraphicsView(self.DataViewTab)
        self.graphicsViewCMOSViewer.setObjectName(_fromUtf8("graphicsViewCMOSViewer"))
        self.gridLayout_4.addWidget(self.graphicsViewCMOSViewer, 2, 0, 3, 1)
        self.graphicsViewHeatmapViewer = GraphicsView(self.DataViewTab)
        self.graphicsViewHeatmapViewer.setObjectName(_fromUtf8("graphicsViewHeatmapViewer"))
        self.gridLayout_4.addWidget(self.graphicsViewHeatmapViewer, 5, 0, 2, 1)
        self.dataViewTextEdit = QtGui.QTextEdit(self.DataViewTab)
        self.dataViewTextEdit.setObjectName(_fromUtf8("dataViewTextEdit"))
        self.gridLayout_4.addWidget(self.dataViewTextEdit, 2, 1, 1, 1)
        self.dataViewerTab.addTab(self.DataViewTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.dataViewerTab, 0, 2, 1, 1)
        self.treeView = QtGui.QTreeView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMinimumSize(QtCore.QSize(350, 0))
        self.treeView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.gridLayout.addWidget(self.treeView, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2392, 31))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.dataViewerTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Brillouin Scanning Interface", None))
        self.session_label.setText(_translate("MainWindow", "Session Name", None))
        self.newSessionBtn.setText(_translate("MainWindow", "New Session", None))
        self.loadSessionBtn.setText(_translate("MainWindow", "Load Session", None))
        self.dataViewerTab.setTabText(self.dataViewerTab.indexOf(self.DataAcqTab), _translate("MainWindow", "Data Acquisition", None))
        self.dataViewInfoDisplay.setText(_translate("MainWindow", "Frame 0/0 ", None))
        self.dataViewerTab.setTabText(self.dataViewerTab.indexOf(self.DataViewTab), _translate("MainWindow", "Data Viewer", None))

from pyqtgraph.parametertree import ParameterTree
from pyqtgraph.widgets.GraphicsView import GraphicsView
